### ISSUE TITLE
use updated zbar version

### ISSUE THREAD

**Issue by lekoala** [samsam2310/zbar.wasm#10]
Do you think you could use an up to date version of zbar instead of 0.10 ? it seems newest version includes lots of fixes

**Comment by samsam2310** [comment]
Yes maybe. Do you have some specific fix or features you want?

**Comment by lekoala** [comment]
i don't think there is any specific feature, as long as it works reliably. I just found out about https://github.com/maslick/koder this project which use an updated version but also does a lot more than what i'm looking for
but maybe there is no real benefits in the newest versions

**Comment by samsam2310** [comment]
Thanks for the context. I used 0.10 because that is the newest version I found in the document when I create the project. I didn't know that there is a fork. But yes using a maintained version should be better.

**Comment by jcs224** [comment]
Can confirm that newer version of zbar is more accurate when scanning images.

**Comment by samsam2310** [comment]
I have planned to do the uprev but it may need some time.
