### ISSUE TITLE
Please provide code from sample site

### ISSUE THREAD

**Issue by mindpivot** [samsam2310/zbar.wasm#2]
Hi there @samsam2310,

I've been unable to get the sample code on the README.md page working. I was wondering if you would be willing to upload the un-minified code used on the page here: https://zbar.chino.taipei/ where you show off the library.

Thank you!

**Comment by samsam2310** [comment]
Hi
The example site is a simple github page and all the code is in the gh-page branch.

If you find any problem in the example, feel free to let me know.

Thanks

**Comment by chenyong** [comment]
demo not working anymore.

**Comment by rognstad** [comment]
The gh-page branch doesn't seem to exist anymore. The source map for https://zbar-wasm.github.io/demo/static/js/index.js is clear, though!

**Comment by samsam2310** [comment]
Yes.
Since my personal domain caused some confusion, I have moved the demo page to another repo.

**Comment by M4GNV5** [comment]
For the people searching: https://github.com/zbar-wasm/demo
