### ISSUE TITLE
Empty result from scanner.scanQrcode

### ISSUE THREAD

**Issue by chenyong** [samsam2310/zbar.wasm#3]
Thanks for compiling the library anyway. I tried to compile it by myself but turned out I have no idea figuring out the errors in running `emmake`, being unfamiliar with C++.

I managed to run the library with a Webpack project. But I kept got `[]` by calling `scanner.scanQrcode`. Since the demo provided in the project has already be down, I can't find a demo to verify if the code still works. Last update from this project is 2 years ago.

I'm also feel a bit confused about bundling the whole thing into our current project in Webpack. Do you have more demos in more details?

**Comment by samsam2310** [comment]
Hi chenyong,

The Github page just broken. It should be fixed now.
All demo source code is in another branch.

**Comment by samsam2310** [comment]
For the emmake failures, maybe the .travis ci script can help.

**Comment by chenyong** [comment]
Thanks.


I suggest using `console.log` instead of `alert`. Then I can see how fast it responds to my code.

**Comment by samsam2310** [comment]
Hi chenyong,

A new version of ZBar.wasm is released. A new demo page based on it is also published. Maybe you want to take a look.
